### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by riffaud** [saintberry/PhantomJs-Extension#1]

**Comment by culleningus** [comment]
Seriously... I tried using this in my java application but it didn't work... I wish there was some advice for a java install in the README.md

![](http://33.media.tumblr.com/83c7505fdf47afb454d1e5b9f3a36f3c/tumblr_inline_nhl18y8AMT1s5i5qt.png)

**Comment by saintberry** [comment]
Fixed in ed9b4e8a1e5b844bf09aad311897682208183e64.
